name: 🐛 Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: dropdown
    id: domain
    attributes:
      label: Domain Area
      description: Which domain area is affected by this bug?
      multiple: true
      options:
        - CV Analysis
        - Job Matching
        - Career Path
        - User Management
        - Infrastructure/Cross-cutting
    validations:
      required: true

  - type: dropdown
    id: architecture
    attributes:
      label: Architectural Layer
      description: Which architectural layer(s) is affected?
      multiple: true
      options:
        - API Layer
        - Application Layer
        - Domain Layer
        - Infrastructure Layer
        - Contracts
        - Shared Abstractions
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: e.g., v1.0.0
    validations:
      required: true

  - type: dropdown
    id: dotnet-version
    attributes:
      label: .NET Version
      options:
        - .NET 8.0
        - .NET 7.0
        - Other (specify in environment)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        examples:
          - **OS**: Windows 10
          - **Database**: MySQL 8.0
          - **Browser**: Chrome 120.0
      value: |
        - OS:
        - Database:
        - Browser:
      render: markdown
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: How do you trigger this bug? Please walk us through it step by step.
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code.
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here. 