blank_issues_enabled: false
contact_links:
  - name: CareerBoostAI Community Support
    url: https://github.com/yourusername/CareerBoostAI/discussions
    about: Please ask and answer questions here. 